Core/code/07.ADF.Web/Pages/ExcelXmlTransform/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.IO;
using System.Text;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Http;
using ADF.IBusiness;
using ADF.Business;


namespace ADF.Web.Pages.ExcelXmlTransform
{
    public class IndexModel : PageModel
    {
        public IActionResult OnPostImport(IFormFile excelfile)
        {
            using (Stream stream = new MemoryStream())
            {
                excelfile.CopyTo(stream);
                stream.Flush();

                IProfessionBussiness profession = new ProfessionBussiness();
                profession.UpdateProfession(stream);
            }
            return Content("OK");

            // string sWebRootFolder = _hostingEnvironment.WebRootPath;
            // string sFileName = $"{Guid.NewGuid()}.xlsx";
            // FileInfo file = new FileInfo(Path.Combine(sWebRootFolder, sFileName));
            // try
            // {
            //     using (FileStream fs = new FileStream(file.ToString(), FileMode.Create))
            //     {
            //         excelfile.CopyTo(fs);
            //         fs.Flush();
            //     }
            //     using (ExcelPackage package = new ExcelPackage(file))
            //     {
            //         StringBuilder sb = new StringBuilder();
            //         ExcelWorksheet worksheet = package.Workbook.Worksheets[1];
            //         int rowCount = worksheet.Dimension.Rows;
            //         int ColCount = worksheet.Dimension.Columns;
            //         bool bHeaderRow = true;
            //         for (int row = 1; row <= rowCount; row++)
            //         {
            //             for (int col = 1; col <= ColCount; col++)
            //             {
            //                 if (bHeaderRow)
            //                 {
            //                     sb.Append(worksheet.Cells[row, col].Value.ToString() + "\t");
            //                 }
            //                 else
            //                 {
            //                     sb.Append(worksheet.Cells[row, col].Value.ToString() + "\t");
            //                 }
            //             }
            //             sb.Append(Environment.NewLine);
            //         }
            //         return Content(sb.ToString());
            //     }
            // }
            // catch (Exception ex)
            // {
            //     return Content(ex.Message);
            // }
        }

        public IActionResult OnGetExport()
        {
            IProfessionBussiness profession = new ProfessionBussiness();
            var stream = profession.ExportProfession();
            stream.Position = 0;
            return File(stream, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");
        }
    }
}

Core/code/07.ADF.Web/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ADF.Web.Pages
{
    public class IndexModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Core/code/07.ADF.Web/Pages/ExcelXmlTransform/Index.cshtml
@page
@model ADF.Web.Pages.ExcelXmlTransform.IndexModel

@{
    ViewData["Title"] = "Index";
}

<h1>病情观察的导入和导出</h1>
<hr/>
<form method="get">
    <a asp-route-handler="Export">导出Excel</a>
</form>

<hr/>
<form enctype="multipart/form-data" method="post" asp-page-handler="Import">
    <input type="file" name="excelfile"/>
    <input type="submit" value="导入Excel"/>
</form>

Core/code/07.ADF.Web/Pages/Index.cshtml
@page
@model ADF.Web.Pages.IndexModel
@{
    ViewData["Title"]="Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Core/code/07.ADF.Web/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>@ViewData["Title"]</title>
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/common.css" />
    </head>
    <body>
      <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand">ADF</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/ExcelXmlTransform/Index">Data Transform</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 Asp.Net Core Razor Pages - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    <script src="~/js/common.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
    </body>
</html>